# Copyright (c) 2022, Dell Inc. or its subsidiaries.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# See the LICENSE file for details.
#
# This file is part of NVMe STorage Appliance Services (nvme-stas).
#
# Authors: Martin Belanger <Martin.Belanger@dell.com>
#

version: 2

python:
  system_packages: true

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  apt_packages:
    - meson
    - python3-lxml
    - docbook-xsl
    - xsltproc
  jobs:
    pre_build:
      - pip3 install lxml
      - python3 -c "import lxml"
      - meson .build --debug --errorlogs -Dreadthedocs=true
      - cat .build/meson-logs/meson-log.txt
      - ninja -C .build

sphinx:
  configuration: .build/doc/conf.py
